enum Status {
  PENDING
  COMPLETED
  CANCELLED
}

type Address {
  street: String
  city: String
  state: String
  postalCode: String
  country: String
}

type Order {
  user: ID
  products: [Product]
  totalAmount: Float
  billingAddress: Address
  shippingAddress: Address
  status: Status
}

input OrderProduct {
  id: ID
  quantity: Int
}

input AddressInput {
  street: String
  city: String
  state: String
  postalCode: String
  country: String
}

input OrderInput {
  user: ID
  products: [OrderProduct]
  billingAddress: AddressInput
  shippingAddress: AddressInput
}

type Query {
  getOrders: [Order]
}

type Mutation {
  createOrder(input: OrderInput): Order
}
