type User {
  id: ID
  firstname: String
  lastname: String
  email: String
  avatar: String
}

input UserInput {
  id: ID
  firstname: String
  lastname: String
  email: String
  password: String
  avatar: String
}

input LoginInput {
  email: String
  password: String
}

input ForgetPassword {
  email: String
  password: String
  newPassword: String
}

type Query {
  allUsers: [User]
  user: User
}

type Mutation {
  register(input: UserInput): User
  login(input: LoginInput): User
  forgetPassword(input: ForgetPassword): User
  logout: Boolean
}
